TriviumStudio/cargodrom-frontend

- src/app/api/custom_models/contact.ts
- src/app/pages/components/contact-editor/contact-editor.component.html
- src/app/pages/components/contact-editor/contact-editor.component.ts
- src/app/pages/components/contractor-editor/contractor-editor.component.html
- src/app/pages/components/contractor-editor/contractor-editor.component.ts
- src/app/pages/services/contact-list.service.spec.ts
- src/app/pages/services/contact-list.service.ts
This PR implements the ability to update, remove, add contacts
> Ability to update, remove, add contacts

- package-lock.json
- package.json
- src/app/auth/auth.module.ts
- src/app/auth/components/login/login.component.spec.ts
- src/app/auth/components/login/login.component.ts
- src/app/material/components/error-dialog/error-dialog-data.ts
- src/app/material/components/error-dialog/error-dialog.component.html
- src/app/material/components/error-dialog/error-dialog.component.spec.ts
- src/app/material/components/error-dialog/error-dialog.component.ts
- src/app/material/material.module.ts
- src/app/pages/pages.module.ts
- src/index.html
- src/styles.scss
This PR adds Angular Material and Error Dialog
> Add Angular Material and Error Dialog

- src/app/pages/components/rating/rating.component.spec.ts
This PR adds tests for Rating Component
> Add tests for rating component

- src/app/pages/components/contractor-editor/contractor-editor.component.html
- src/app/pages/components/contractor-editor/contractor-editor.component.ts
This PR implements ability to remove contractor
> Ability to remove contractor

- src/app/pages/components/contractor-editor/contractor-editor.component.ts
- src/app/pages/components/contractor-filter/contractor-filter.component.ts
- src/app/pages/services/city.service.spec.ts
- src/app/pages/services/city.service.ts
- src/app/pages/services/country.service.spec.ts
- src/app/pages/services/country.service.ts
Create Country and City Services that store and load data in localStorage
> Create Country and City Services

- src/app/pages/components/contact-editor/contact-editor.component.html
- src/app/pages/components/contact-editor/contact-editor.component.ts
- src/app/pages/components/contractor-editor/contractor-editor.component.html
- src/app/pages/components/contractor-editor/contractor-editor.component.ts
- src/app/pages/components/rating/rating.component.ts
This MR improves contactor editor validation
> Improve contactor editor validation

- src/app/pages/components/paginator/paginator.component.html
- src/app/pages/components/paginator/paginator.component.spec.ts
- src/app/pages/components/paginator/paginator.component.ts
This PR uses mat-select for paginator.
> Styles for paginator

- src/app/api/services/contractor.service.ts
This PR updates contractor API
> Update contractor API

- src/app/pages/components/responsibility-editor/responsibility-editor.component.html
This PR adds pluralization for word `country`
> Add pluralization for word country

- src/app/pages/components/contractor-editor/contractor-editor.component.ts
- src/app/pages/components/trade-direction/trade-direction.component.ts
* Get rid of "value changed after checked error"
* Remove country name from trade direction
* Remove console.table
> Contactor editor minor improvements

- src/app/api/services/user.service.ts
This PR updates User API using latest Open API schema.
> Update User API

- src/app/constants/index.ts
- src/app/constants/sort-predicate.ts
- src/app/pages/modules/settings/components/position-editor/position-editor.component.ts
- src/app/pages/modules/settings/components/position/position.component.ts
This PR makes pagination work for positions.
> Make pagination work for positions

- src/app/pages/modules/settings/components/personal-settings/personal-settings.component.html
- src/app/pages/modules/settings/components/personal-settings/personal-settings.component.spec.ts
- src/app/pages/modules/settings/components/personal-settings/personal-settings.component.ts
- src/app/pages/modules/settings/settings-routing.module.ts
- src/app/pages/modules/settings/settings.module.ts
This PR adds a mockup for Personal Settings
> Personal Settings Mockup

- src/app/api/custom_models/index.ts
- src/app/api/custom_models/tax-system.ts
- src/app/api/services/settings.service.ts
- src/app/pages/modules/settings/components/company-editor/company-editor.component.html
- src/app/pages/modules/settings/components/company-editor/company-editor.component.spec.ts
- src/app/pages/modules/settings/components/company-editor/company-editor.component.ts
This PR adds Tax System field to Company Editor
> Add Tax System into Company Editor

- angular.json
This MR sets RU as a default locale
> Build for Russian locale

- angular.json
Signed-off-by: Leonty Chudinov <leonty.chudinov@gmail.com>
> Set Locale to ru

- .github/workflows/gh-pages.yml
Signed-off-by: Leonty Chudinov <leonty.chudinov@gmail.com>
> Update githbub action

- src/app/app.module.ts
Signed-off-by: Leonty Chudinov <leonty.chudinov@gmail.com>
> Load Russian locale

- src/app/constants/sort-predicate.ts
- src/app/pages/modules/settings/components/department/department.component.html
- src/app/pages/modules/settings/components/department/department.component.ts
Implement sorting for Department component
> Implement sorting for Department component

- src/app/pages/modules/settings/components/company/company.component.ts
- src/app/pages/modules/settings/components/employee/employee.component.ts
- src/app/pages/modules/settings/components/position/position.component.ts
This PR implements pagination for Employee Component and minor fixes for pagination for other components
> Pagination for Employee Component and minor fixes for pagination for other components

- src/app/pages/modules/settings/components/department/department.component.html
- src/app/pages/modules/settings/components/department/department.component.ts
- src/app/pages/modules/settings/components/employee/employee.component.html
- src/app/pages/modules/settings/components/employee/employee.component.ts
Signed-off-by: Leonty Chudinov <leonty.chudinov@gmail.com>
> Add Confirmation Dialog for Remove Action

- src/app/pages/modules/settings/components/department-employee/department-employee.component.html
- src/app/pages/modules/settings/components/employee-editor/employee-editor.component.html
- src/app/pages/modules/settings/components/employee-editor/employee-editor.component.ts
- Department Employee: Show table header only if there are employees
- Employee Editor: disable Department select box when department is set
> Minor fixes for Department Employee and Employee Editor

- src/app/pages/modules/settings/components/department-employee/department-employee.component.html
- src/app/pages/modules/settings/components/department-employee/department-employee.component.ts
- Load Positions on init
- Fix edit employee link
> Minor fixes for Department Employee

- src/app/pages/modules/settings/components/company/company.component.html
- src/app/pages/modules/settings/components/company/company.component.spec.ts
- src/app/pages/modules/settings/components/company/company.component.ts
This PR shows responsible person in company editor
> Show responsible person

- src/app/pages/components/contractor-editor/contractor-editor.component.html
- src/app/pages/components/contractor-editor/contractor-editor.component.spec.ts
- src/app/pages/components/contractor-editor/contractor-editor.component.ts
This PR is to Load Tax Systems in Contactor Editor
> Load Tax Systems in Contactor Editor

- src/app/auth/services/auth.service.ts
- src/app/pages/modules/settings/components/personal-settings/personal-settings.component.ts
- src/app/pages/modules/settings/settings-routing.module.ts
- Save token in local storage
- Add message duration in personal settings
- Redirect to personal settings by default
> MInor fixes

- src/app/api/custom_models/department.ts
- src/app/api/services/company.service.ts
- src/app/pages/modules/settings/components/department/department.component.html
- src/app/pages/modules/settings/components/department/department.component.spec.ts
- src/app/pages/modules/settings/components/department/department.component.ts
> Display department leader

- src/app/error.interceptor.spec.ts
- src/app/error.interceptor.ts
Navigate to login in case of 401 or 403
> Navigate to login in case of 401 or 403

- src/app/material/directives/focus-initial.directive.spec.ts
- src/app/material/directives/focus-initial.directive.ts
- src/app/material/material.module.ts
- src/app/pages/components/contractor-editor/contractor-editor.component.html
- src/app/pages/modules/settings/components/company-editor/company-editor.component.html
- src/app/pages/modules/settings/components/department-editor/department-editor.component.html
- src/app/pages/modules/settings/components/employee-editor/employee-editor.component.html
- src/app/pages/modules/settings/components/personal-settings/personal-settings.component.html
- src/app/pages/modules/settings/components/position-editor/position-editor.component.html
Focus initial elements in forms
> Focus initial elements in forms

- src/app/pages/modules/settings/components/employee-editor/employee-editor.component.ts
Include disabled fields into employee form value
> Include disabled fields into employee form value

- src/app/pages/modules/settings/components/employee/employee.component.html
- src/app/pages/modules/settings/components/employee/employee.component.ts
Improve Employee Table loading
> Improve Employee Table loading

- src/app/cargodrom.css
- src/app/pages/modules/settings/components/employee-editor/employee-editor.component.html
- src/app/pages/modules/settings/components/employee-editor/employee-editor.component.ts
This PR adds validation for employee editor component
> Add validation for employee editor component

- src/app/auth/components/register/register.component.ts
- src/app/pages/modules/settings/components/company-editor/company-editor.component.html
- src/app/pages/modules/settings/components/company-editor/company-editor.component.ts
- src/app/pages/modules/settings/components/employee-editor/employee-editor.component.ts
- src/app/validators/index.ts
- src/app/validators/inn-validator.ts
- src/app/validators/pattern-validator.ts
Add validation for company editor
> Add validation for company editor

- package-lock.json
- package.json
- src/app/app.module.ts
- src/app/pages/modules/settings/components/company-editor/company-editor.component.html
- src/app/pages/modules/settings/components/company-editor/company-editor.component.ts
- src/app/pages/modules/settings/components/company/company.component.html
- src/app/pages/modules/settings/components/employee-editor/employee-editor.component.html
- src/app/pages/modules/settings/components/employee-editor/employee-editor.component.ts
- src/app/pages/modules/settings/components/employee/employee.component.html
- src/app/pages/modules/settings/components/personal-settings/personal-settings.component.html
- src/app/pages/modules/settings/settings-routing.module.ts
- src/app/pages/modules/settings/settings.module.ts
> Use masked inputs

- src/app/pages/modules/settings/classes/settings-editor.ts
- src/app/pages/modules/settings/components/company-editor/company-editor.component.spec.ts
- src/app/pages/modules/settings/components/company/company.component.html
- src/app/pages/modules/settings/components/department-editor/department-editor.component.spec.ts
- src/app/pages/modules/settings/components/department-employee/department-employee.component.html
- src/app/pages/modules/settings/components/department/department.component.html
- src/app/pages/modules/settings/components/employee-editor/employee-editor.component.spec.ts
- src/app/pages/modules/settings/components/employee/employee.component.html
- src/app/pages/modules/settings/components/position-editor/position-editor.component.spec.ts
- src/app/pages/modules/settings/components/position/position.component.html
- src/app/pages/modules/settings/settings-routing.module.ts
> Improve settings routing

- src/app/api/specs/company.service.spec.ts
- src/app/pages/modules/settings/classes/settings-editor.ts
- src/app/pages/modules/settings/components/company-editor/company-editor.component.ts
- src/app/pages/modules/settings/components/department-editor/department-editor.component.ts
- src/app/pages/modules/settings/components/employee-editor/employee-editor.component.ts
- src/app/pages/modules/settings/components/position-editor/position-editor.component.ts
Refactoring for Settings Editors
> Refactoring for settings editors

- src/app/api/services/company.service.ts
- src/app/pages/modules/settings/classes/settings-editor.ts
- src/app/pages/modules/settings/components/company-editor/company-editor.component.spec.ts
- src/app/pages/modules/settings/components/company/company.component.spec.ts
- src/app/pages/modules/settings/components/company/company.component.ts
- src/app/pages/modules/settings/components/department-editor/department-editor.component.spec.ts
- src/app/pages/modules/settings/components/department-employee/department-employee.component.spec.ts
- src/app/pages/modules/settings/components/department-employee/department-employee.component.ts
- src/app/pages/modules/settings/components/department/department.component.spec.ts
- src/app/pages/modules/settings/components/department/department.component.ts
- src/app/pages/modules/settings/components/employee-editor/employee-editor.component.spec.ts
- src/app/pages/modules/settings/components/employee/employee.component.spec.ts
- src/app/pages/modules/settings/components/employee/employee.component.ts
- src/app/pages/modules/settings/components/position-editor/position-editor.component.spec.ts
- src/app/pages/modules/settings/components/position/position.component.spec.ts
- src/app/pages/modules/settings/components/position/position.component.ts
Update Settings Editors to use items key
> Update Settings Editors to use items key

- src/app/pages/modules/settings/components/department-employee/department-employee.component.html
Fix link to edit employee in Department Employee Component
> Fix link to edit employee in Department Employee Component

- src/app/pages/modules/settings/classes/settings-editor.ts
- src/app/pages/modules/settings/components/company-editor/company-editor.component.ts
- src/app/pages/modules/settings/components/department-editor/department-editor.component.ts
- src/app/pages/modules/settings/components/employee-editor/employee-editor.component.ts
- src/app/pages/modules/settings/components/position-editor/position-editor.component.ts
- src/app/pages/modules/settings/settings.component.ts
- Expand only active section when settings activated
- Switch to edit mode when a new entity created
- Stay on the same page when saved
> Settings minor improvements

- src/app/material/components/editor-header/editor-header.component.html
- src/app/material/components/editor-header/editor-header.component.ts
- src/app/pages/components/contractor-editor/contractor-editor.component.html
- src/app/pages/components/contractor-editor/contractor-editor.component.ts
- src/app/pages/modules/settings/classes/settings-editor.ts
- src/app/pages/modules/settings/components/company-editor/company-editor.component.html
- src/app/pages/modules/settings/components/company-editor/company-editor.component.ts
- src/app/pages/modules/settings/components/department-editor/department-editor.component.html
- src/app/pages/modules/settings/components/department-editor/department-editor.component.ts
- src/app/pages/modules/settings/components/employee-editor/employee-editor.component.html
- src/app/pages/modules/settings/components/employee-editor/employee-editor.component.ts
- src/app/pages/modules/settings/components/position-editor/position-editor.component.html
- src/app/pages/modules/settings/components/position-editor/position-editor.component.ts
This MR displays Entity Name in Editor Header
> Display Entity Name in Editor Header

- src/app/api/custom_models/client-filter.ts
- src/app/api/services/customer.service.ts
- src/app/cargodrom.css
- src/app/pages/components/client-editor/client-editor.component.html
- src/app/pages/components/client-editor/client-editor.component.ts
- src/app/pages/components/client-filter/client-filter.component.html
- src/app/pages/components/client-filter/client-filter.component.ts
- Make Contact FIO mandatory
- Pickup filtering API
- Right align controls at the bottom of Client Editor
> Minor improvements for Clients

- src/app/api/custom_models/client.ts
- src/app/api/custom_models/file-document.ts
- src/app/api/services/customer.service.ts
- src/app/api/services/file.service.ts
- src/app/app.module.ts
- src/app/cargodrom.css
- src/app/classes/editor.ts
- src/app/classes/table.ts
- src/app/pages/components/client-editor/client-editor.component.html
- src/app/pages/components/client-filter/client-filter.mockup.ts
- src/app/pages/components/client/client.component.html
- src/app/pages/components/client/client.component.ts
- src/app/pages/components/file-list/file-list.component.ts
- src/app/typings.d.ts
This PR reworks Client Table using Column Definitions.
Also, the PR fixes the File List Component.
> Use Column Definitions

- src/app/cargodrom.css
- src/app/material/material.module.ts
- src/app/pages/components/client/client.component.html
- src/app/pages/components/client/client.component.spec.ts
This PR reworks Client Table using Angualr Material Table.
> Rework Client Table with Material Table

- src/app/cargodrom.css
> Override mat table styles

- src/app/cargodrom.css
- src/app/pages/components/client-editor/client-editor.component.html
- src/app/pages/components/client/client.component.html
> Add Edit button for client table

- src/app/api/services/contractor.service.ts
Update API for Contractor Specialization
> Update API for Contractor Specialization

- src/app/filter/services/filter.service.ts
Apply filter when reset clicked
> Apply filter on reset

- src/app/cargodrom.css
This PR fixs path to the select arrow picture
> Fix path to select arrow

- src/app/api/custom_models/contact.ts
- src/app/api/custom_models/country.ts
- src/app/api/services/contractor.service.ts
- src/app/api/services/direction.service.ts
- src/app/pages/components/contact-editor/contact-editor.component.ts
- src/app/pages/components/responsibility-editor/responsibility-editor.component.ts
> Adapt responsibility editor for new schema

- src/app/classes/table.ts
- src/app/filter/services/filter.service.ts
- src/app/pages/components/client/client.component.spec.ts
- src/app/pages/components/responsibility-editor/responsibility-editor.component.html
- src/app/pages/components/responsibility-editor/responsibility-editor.component.ts
- Isolate local transportation
- Load filter schema only once
- Allow empty import
> Prepare for implementing export responsibility

- src/app/pages/components/contractor/contractor.component.html
- src/app/pages/components/responsibility-editor/responsibility-editor.component.ts
Minor fixes for Contractor
- Rename import to export in Responsibility editor
- Add Edit icon in Contractor table (no styles so far)
> Minor fixes for Contactor

- src/app/api/custom_models/contact.ts
- src/app/cargodrom.css
- src/app/constants/index.ts
- src/app/constants/unknown-country.ts
- src/app/pages/components/contact-editor/contact-editor.component.ts
- src/app/pages/components/responsibility-matrix/responsibility-matrix.component.html
- src/app/pages/components/responsibility-matrix/responsibility-matrix.component.spec.ts
- src/app/pages/components/responsibility-matrix/responsibility-matrix.component.ts
- src/app/pages/components/responsibility-row/responsibility-row.component.html
- src/app/pages/components/responsibility-row/responsibility-row.component.spec.ts
- src/app/pages/components/responsibility-row/responsibility-row.component.ts
> Refactor Responsibility Components

- src/app/app-routing.module.ts
- src/app/app.module.ts
- src/app/page-title.service.spec.ts
- src/app/page-title.service.ts
- src/app/pages/modules/settings/settings-routing.module.ts
- src/app/pages/pages-routing.module.ts
> Assign Title to Pages

- src/app/app.module.ts
- src/app/classes/editor.ts
- src/app/constants/index.ts
- src/app/constants/mask.ts
- src/app/material/directives/phone-mask.directive.spec.ts
- src/app/material/directives/phone-mask.directive.ts
- src/app/material/material.module.ts
- src/app/pages/components/client-editor/client-editor.component.html
- src/app/pages/modules/settings/components/company-editor/company-editor.component.html
- src/app/pages/modules/settings/components/company/company.component.html
- src/app/pages/modules/settings/components/employee-editor/employee-editor.component.html
- src/app/pages/modules/settings/components/employee/employee.component.html
- src/app/pages/modules/settings/components/personal-settings/personal-settings.component.html
- src/app/pages/pages.module.ts
> Use custom phoneMask directive instead of NgxMask

- src/app/cargodrom.css
- src/app/classes/table.ts
- src/app/pages/components/contractor/contractor.component.html
- src/app/pages/components/contractor/contractor.component.scss
- Don't display sort hints on non-sortable columns
> Follow-up Fixes for Client

- src/app/pages/components/contact-editor/contact-editor.component.html
- src/app/pages/components/contractor-editor/contractor-editor.component.html
> Add phone mask in contractor

- src/app/api/api.module.ts
- src/app/api/custom_models/contractor.ts
- src/app/api/services.ts
- src/app/api/services/contractor.service.ts
- src/app/api/services/file.service.ts
- src/app/api/services/page.service.ts
- src/app/cargodrom.css
- src/app/pages/components/contractor/contractor.component.html
> Display Contractor Specialization and Container

- src/app/pages/components/client-editor/client-editor.component.html
- src/app/pages/components/client-editor/client-editor.component.ts
- src/app/pages/components/file-list/file-list.component.html
- src/app/pages/components/file-list/file-list.component.spec.ts
- src/app/pages/components/file-list/file-list.component.ts
> Make documents path work in Client Editor

- src/app/cargodrom.css
- src/app/pages/components/contractor/contractor.component.html
> Rework Contractor Table

- src/app/api/services/contractor.service.ts
- src/app/api/services/request.service.ts
- src/app/classes/table.ts
- src/app/pages/components/client/client.component.html
- src/app/pages/components/contractor/contractor.component.html
- src/app/pages/components/contractor/contractor.component.ts
> Implement Export for Contractor

- src/app/classes/table.ts
- src/app/pages/components/client/client.component.html
- src/app/pages/components/contractor/contractor.component.html
This MR adds confiration dialog for export operation.
> Add confirmation dialog for export

- src/app/classes/table.ts
- src/app/pages/components/client/client.component.html
- src/app/pages/components/contractor/contractor.component.html
> Add Confirmation for Import

- src/app/pages/components/contractor/contractor.component.html
теперь для доступа к возможности сохранить данные достаточно одного из двух полей(insert или update)
> изменил логику отображения кнопки сохр.дан

- src/app/api/custom_models/counterparty.ts
- src/app/api/services/contractor.service.ts
- src/app/api/services/customer.service.ts
- src/app/api/services/request.service.ts
- src/app/pages/components/contractor-editor/contractor-editor.component.html
- src/app/pages/components/contractor-editor/contractor-editor.component.scss
- src/app/pages/components/contractor-editor/contractor-editor.component.spec.ts
- src/app/pages/components/contractor-editor/contractor-editor.component.ts
1. "Исключить Подрядчика из торгов" переделываем в "Участник торгов" Инверсия
Переменная allow_trade
2. рядом добавляем Селект "Вид подрядчика" 
метод /contractor_type будет новый список: "Индикатив", "Актуальный", "Архив"
Переменная type_id
Если "Актуальный", то "Контактное лицо" является обязательным, "Индикатив" и "Архив" не обязательно 
(это не сделал)
3. Существующий "Вид подрядчика" меняем на "Тип контрагента" 
Метод /system_counterparty
counterparty_id
> Contaractor form

- src/app/api/services/contractor.service.ts
- src/app/api/services/request.service.ts
- src/app/classes/table.ts
- src/app/pages/components/contractor/contractor.component.html
- src/app/pages/components/contractor/contractor.component.ts
-добавлена кнопка ШАБЛОН ДЛЯ ИМПОРТА, при нажатии скачивается Excel файл шаблон
> +экспорт шаблона

- src/app/api/custom_models/contact.ts
- src/app/api/services/contractor.service.ts
- src/app/api/services/customer.service.ts
- src/app/api/services/request.service.ts
- src/app/pages/components/contact-editor/contact-editor.component.html
- src/app/pages/components/contact-editor/contact-editor.component.scss
- src/app/pages/components/contact-editor/contact-editor.component.spec.ts
- src/app/pages/components/contact-editor/contact-editor.component.ts
- src/app/pages/components/contractor-editor/contractor-editor.component.ts
- src/app/pages/components/contractor/contractor.component.ts
- src/app/pages/components/responsibility-matrix/responsibility-matrix.component.ts
- src/app/pages/components/responsibility/responsibility.component.html
- src/app/pages/components/responsibility/responsibility.component.scss
- src/app/pages/components/responsibility/responsibility.component.ts
- src/app/pages/pages.module.ts
Изменил логику, нужны доработки по дизайну
> Зоны ответственности контактов в подрядчиках

- src/app/api/custom_models/request.ts
- src/app/api/services/cargo.service.ts
- src/app/api/services/file.service.ts
- src/app/api/services/request.service.ts
- src/app/api/services/transport.service.ts
- src/app/material/material.module.ts
- src/app/pages/components/rate-editor/rate-editor.component.html
- src/app/pages/components/rate-editor/rate-editor.component.ts
- src/app/pages/components/request-editor/request-editor.component.html
- src/app/pages/components/request-editor/request-editor.component.ts
- src/app/pages/components/request-rate/request-rate.component.html
- src/app/pages/components/request-rate/request-rate.component.scss
- src/app/pages/components/request-rate/request-rate.component.ts
- src/app/pages/components/request/request.component.ts
- src/app/pages/components/responsibility/responsibility.component.html
- src/app/pages/components/responsibility/responsibility.component.scss
- src/app/pages/components/responsibility/responsibility.component.ts
- src/app/pages/pages-routing.module.ts
- src/app/pages/pages.module.ts
изменил зоны ответственности, рейты еще в процессе
> Rate request
